###
GET http://localhost:2394/api/mate/page/0
content-type: application/json
identifyId: uJyZ1KPQpsTFuTcAAOwOZDRYhfu1
userId: 6256d1101014841df59a4975

###
POST http://localhost:2394/api/mate
content-type: application/json
identifyId: uJyZ1KPQpsTFuTcAAOwOZDRYhfu1
userId: 6256d1101014841df59a4975

{
    "images": ["https://firebasestorage.googleapis.com/v0/b/shoppingmate-652c6.appspot.com/o/sample_female_dendy_1.jpeg?alt=media&token=b47c1748-9763-43e7-b006-70ec360fdd19", "https://firebasestorage.googleapis.com/v0/b/shoppingmate-652c6.appspot.com/o/sample_female_over_fit_1.jpeg?alt=media&token=6496575b-fd3e-4a7c-a6fc-9ec483821a60"],
    "title": "7777",
    "message": "77777",
    "locationStr": "동묘 구재시장",
    "tags": ["사랑", "합니다", "즐기자"]
}

###
GET http://localhost:2394/api/tag/search/word/꽃놀이/dress/0
content-type: application/json
identifyId: uJyZ1KPQpsTFuTcAAOwOZDRYhfu1
userId: 6256d1101014841df59a4975

###
GET http://localhost:2394/api/mate/detail/625d75925fcd1ca509692024
content-type: application/json
identifyId: uJyZ1KPQpsTFuTcAAOwOZDRYhfu1
userId: 6256d1101014841df59a4975


###
POST http://localhost:2394/api/mate/join/625d75925fcd1ca509692024
content-type: application/json
identifyId: AuRZj4QtqBegIQJxcAXlkFXsThc2
userId: 625c28721014841df59a4a9d


###
POST http://localhost:2394/api/mate/join/625d75925fcd1ca509692024
content-type: application/json
identifyId: XWK5rLSr8JM18gxIBSiUWWL9WUd2
userId: 6252cce487194a3e052fe240


###
POST http://localhost:2394/api/mate/accept/625d75925fcd1ca509692024
content-type: application/json
identifyId: uJyZ1KPQpsTFuTcAAOwOZDRYhfu1
userId: 6256d1101014841df59a4975

{
    "joinMemberId": "6252cce487194a3e052fe240"
}


###
POST http://localhost:2394/api/mate/separate/625d75925fcd1ca509692024
content-type: application/json
identifyId: AuRZj4QtqBegIQJxcAXlkFXsThc2
userId: 625c28721014841df59a4a9d


###
POST http://localhost:2394/api/mate/separate/625d75925fcd1ca509692024
content-type: application/json
identifyId: XWK5rLSr8JM18gxIBSiUWWL9WUd2
userId: 6252cce487194a3e052fe240

