###
GET http://localhost:2394/api/sign
content-type: application/json
identifyId: admin
userId: 1


###
POST http://localhost:2394/api/sign/signin
content-type: application/json
identifyId: admin
userId: 1

{
    "identifyId": "zxkcjhiqwuezxd",
    "email": "kadasdakaa@gmail.com"
}