

###
GET http://localhost:2394/api/dress/count/2
content-type: application/json
identifyId: 7qsZtIQr6FbEgYU5O3zjH7bxLcm2
userId: 6256d1361014841df59a497f


###
GET http://localhost:2394/api/dress/detail/625557ae6257cfa39062607c
content-type: application/json
# identifyId: 7qsZtIQr6FbEgYU5O3zjH7bxLcm2
# userId: 6256d1361014841df59a497f

###
GET http://localhost:2394/api/dress/user/6256d1361014841df59a497f/DATE/0
content-type: application/json
identifyId: 7qsZtIQr6FbEgYU5O3zjH7bxLcm2
userId: 6256d1361014841df59a497f

###
POST http://localhost:2394/api/dress
content-type: application/json
identifyId: 7qsZtIQr6FbEgYU5O3zjH7bxLcm2
userId: 6256d1361014841df59a497f

{
    "images" : ["https://smate.s3.ap-northeast-2.amazonaws.com/sample_female_semi_formal_1.jpeg", "https://smate.s3.ap-northeast-2.amazonaws.com/sample_female_semi_formal_2.jpeg"],
    "say": "하하하 #봄#데이트#준비했지#꽃놀이",
    "tags": ["봄","데이트", "준비했지", "꽃놀이"]
}

###
POST http://localhost:2394/api/reply
content-type: application/json
identifyId: uJyZ1KPQpsTFuTcAAOwOZDRYhfu1
userId: 6256d1101014841df59a4975

{
    "owner": "6256d1101014841df59a4975",
    "parent": "6256d24b9f2ca2c1716a19b5",
    "say": "옷 이쁘네요!"
}

###
PATCH http://localhost:2394/api/dress/like
content-type: application/json
identifyId: uJyZ1KPQpsTFuTcAAOwOZDRYhfu1
userId: 6256d1101014841df59a4975

{
    "dressId": "6256d24b9f2ca2c1716a19b5"
}

###
GET http://localhost:2394/api/user/me
content-type: application/json
identifyId: uJyZ1KPQpsTFuTcAAOwOZDRYhfu1
userId: 6256d1101014841df59a4975


