
###
GET http://localhost:2394/api/user/me
content-type: application/json
identifyId: uJyZ1KPQpsTFuTcAAOwOZDRYhfu1
userId: 6256d1101014841df59a4975

###
GET http://localhost:2394/api/user/detail/me
content-type: application/json
identifyId: 6aGMeuLgbSdQlSW6TPOTf3OoEA12
userId: 626e7c1584af6260aeb8d8f8

###
GET http://localhost:2394/api/user/check/nickName/haha2
content-type: application/json
identifyId: uJyZ1KPQpsTFuTcAAOwOZDRYhfu1
userId: 6256d1101014841df59a4975



//Test01
# identifyId: 2YQe8iVMtUMK4S8nSf3xwdEf6Nd2
# userId: 626e7bed84af6260aeb8d8d6
//Test02
# identifyId: u3bCWQjSnygYP23WDxEQHk4Fxoq1
# userId: 626e7c0084af6260aeb8d8e7
//Test03
# identifyId: 6aGMeuLgbSdQlSW6TPOTf3OoEA12
# userId: 626e7c1584af6260aeb8d8f8

