###
GET http://localhost:2394/api/mate/page/0
content-type: application/json
identifyId: uJyZ1KPQpsTFuTcAAOwOZDRYhfu1
userId: 6256d1101014841df59a4975

###
POST http://localhost:2394/api/mate
content-type: application/json
identifyId: YoBzWK7RcxT47EIboAAayWydup22
userId: 626a21e24dd6978e07e8754e

{
    "images": ["https://firebasestorage.googleapis.com/v0/b/shoppingmate-652c6.appspot.com/o/sample_female_dendy_1.jpeg?alt=media&token=b47c1748-9763-43e7-b006-70ec360fdd19", "https://firebasestorage.googleapis.com/v0/b/shoppingmate-652c6.appspot.com/o/sample_female_over_fit_1.jpeg?alt=media&token=6496575b-fd3e-4a7c-a6fc-9ec483821a60"],
    "title": "가자 쇼핑하러333322",
    "message": "가가자자자자자 쇼핑하고 맛있는 맛집도 들러요. #봄날씨 #데이트 #맛집",
    "locationStr": "동묘 구재시장",
    "tags": ["봄날씨", "데이트", "맛집"]
}

###
GET http://localhost:2394/api/tag/search/word/꽃놀이/dress/0
content-type: application/json
identifyId: uJyZ1KPQpsTFuTcAAOwOZDRYhfu1
userId: 6256d1101014841df59a4975

###
GET http://localhost:2394/api/mate/detail/625d75925fcd1ca509692024
content-type: application/json
identifyId: uJyZ1KPQpsTFuTcAAOwOZDRYhfu1
userId: 6256d1101014841df59a4975


###
POST http://localhost:2394/api/mate/join/625d748a59a35aad7f4b1cd0
content-type: application/json
identifyId: EsZsHQSNwGbfVvTvYagqs0Snxrz2
userId: 625ad4ac1014841df59a4a25


###
POST http://localhost:2394/api/mate/join/626b46cb8c2f69d2cf0024c2
content-type: application/json
identifyId: uJyZ1KPQpsTFuTcAAOwOZDRYhfu1
userId: 6256d1101014841df59a4975

###
POST http://localhost:2394/api/mate/accept/625d748a59a35aad7f4b1cd0
content-type: application/json
identifyId: uJyZ1KPQpsTFuTcAAOwOZDRYhfu1
userId: 6256d1101014841df59a4975

{
    "joinMemberId": "625ad4ac1014841df59a4a25"
}


###
POST http://localhost:2394/api/mate/separate/625d75925fcd1ca509692024
content-type: application/json
identifyId: AuRZj4QtqBegIQJxcAXlkFXsThc2
userId: 625c28721014841df59a4a9d


###
POST http://localhost:2394/api/mate/separate/625d75925fcd1ca509692024
content-type: application/json
identifyId: XWK5rLSr8JM18gxIBSiUWWL9WUd2
userId: 6252cce487194a3e052fe240


###
GET http://localhost:2394/api/mate/created/page/0
content-type: application/json
identifyId: uJyZ1KPQpsTFuTcAAOwOZDRYhfu1
userId: 6256d1101014841df59a4975


###
GET http://localhost:2394/api/mate/join/page/0
content-type: application/json
identifyId: uJyZ1KPQpsTFuTcAAOwOZDRYhfu1
userId: 6256d1101014841df59a4975



###
GET http://localhost:2394/api/mate/join/page/0
content-type: application/json
identifyId: EsZsHQSNwGbfVvTvYagqs0Snxrz2
userId: 625ad4ac1014841df59a4a25

